apiVersion: v1

kind: Pod  # Pods = runs one or more closely related container

metadata:
  name: client-pod
  labels:
    component: web

spec:
  containers:
    - name: client
      image: ggabmc/multi-client
      ports:
        - containerPort: 3000